### PR TITLE
Development

### PR DESCRIPTION
**Pull request by Superior212**
Created the reusable components "footer" and "Navbar"

### CODE REVIEW

**Comment by Superior212** [comment]
@ScottDeev Kindly check it out so that we can merge to the main branch

**Comment by ScottDeev** [comment]
Looks good. Checked it out already

**Comment by Superior212** [comment]
Alright

**Comment by Superior212** [comment]
We can go ahead and merge

**Comment by ScottDeev** [comment]
Yes, Let me merge it

**Pull request merged**
